clash_cfg_dir: ~/.local/proxy/mihomo
clash_cfg_path: ~/.local/proxy/mihomo/config.yaml
clash_core_path: /usr/bin/mihomo
clash_srv_name: mihomo
clash_srv_is_user: false
edit_cmd: alacritty -e nvim %s
open_dir_cmd: alacritty -e ranger %s
